name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  DOCKER_BUILDKIT: 1

stages:
  ##############################################################################################
  # Build Stage
  # - Build and Test SourceHub Front End
  # - Build and Test SourceHub Back End
  # - Validate Dev Deploy
  # - Validate Test Deploy
  # - Package SourceHub
  #
  # NOTES:
  # - Build and Validate jobs run in parallel
  # - Once Build and Validate jobs are successful, then the Package SourceHub job commences.
  ###############################################################################################
  - stage: build
    displayName: Build Stage
    jobs:
      - job: packageSourceHub
        displayName: Package SourceHub
        condition: succeeded()
        steps:
          - template: .azure-pipelines/sourcehub-base.build.yml

          - task: ECRPushImage@1
            displayName: Push SourceHub Base Image to ECR
            inputs:
              awsCredentials: "Apollo-AWS-Dev-Apollo"
              regionName: "us-east-1"
              imageSource: "imagename"
              sourceImageName: "sourcehub-base"
              sourceImageTag: "latest"
              repositoryName: "sourcehub-base"
              pushTag: "latest"

          - template: .azure-pipelines/sourcehub-app.build.yml

          - script: |
              docker run -id --name test sourcehub-app:$(Build.BuildNumber)
              docker exec test bash -lc ". ./venv/bin/activate && pytest --junitxml='RESULTS.xml'"
              TEST_EXIT_CODE=$?
              docker cp test:/home/user/backend/RESULTS.xml RESULTS.xml
              docker stop test
              exit $TEST_EXIT_CODE
            displayName: Test SourceHub
            continueOnError: false

          - task: PublishTestResults@2
            displayName: Publish Test Results
            condition: succeededOrFailed()
            inputs:
              testResultsFiles: "**/RESULTS*.xml"
              testRunTitle: "Test Results for SourceHub-$(Build.BuildNumber)"

          - task: ECRPushImage@1
            displayName: Push SourceHub App Image to ECR as SourceVersion
            inputs:
              awsCredentials: "Apollo-AWS-Dev-Apollo"
              regionName: "us-east-1"
              imageSource: "imagename"
              sourceImageName: "sourcehub-app"
              sourceImageTag: "$(Build.SourceVersion)"
              repositoryName: "sourcehub-app"
              pushTag: "$(Build.SourceVersion)"

          - task: ECRPushImage@1
            displayName: Push SourceHub App Image to ECR as latest
            inputs:
              awsCredentials: "Apollo-AWS-Dev-Apollo"
              regionName: "us-east-1"
              imageSource: "imagename"
              sourceImageName: "sourcehub-app"
              sourceImageTag: "$(Build.SourceVersion)"
              repositoryName: "sourcehub-app"
              pushTag: latest

      - job: validateDevDeploy
        displayName: Validate and Plan Dev Deployment
        steps:
          - template: .azure-pipelines/source-hub.validate.yml
            parameters:
              environment: dev
              awsCredentials: "Apollo-AWS-Dev-Apollo"

      - job: validateTstDeploy
        displayName: Validate and Plan Test Deployment
        steps:
          - template: .azure-pipelines/source-hub.validate.yml
            parameters:
              environment: tst
              awsCredentials: "Apollo-AWS-Test-Apollo"

      - job: validatePrdDeploy
        displayName: Validate and Plan Prod Deployment
        steps:
          - template: .azure-pipelines/source-hub.validate.yml
            parameters:
              environment: prd
              awsCredentials: "Apollo-AWS-Prod-Apollo"

  ##############################################################################################
  # Stage: Deploy to the Development Environment
  #
  # - It is assumed that the container images have been pushed to Dev ECR in the Build Stage
  # - This stage will use a template for the deployment job
  # - This stage can be executed using either the main branch or a feature/* branch. Executing
  #   from a feature/ branch requires a manual trigger.
  ##############################################################################################
  - stage: development
    displayName: Development Stage
    dependsOn: build
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/')))
    jobs:
      - deployment: dev_deployment
        displayName: Deploy to SourceHub Dev
        environment: SourceHub-Dev
        strategy:
          runOnce:
            deploy:
              steps:
                ##
                # Deploy SourceHub to Dev environment
                ##
                - template: .azure-pipelines/source-hub.deploy.yml
                  parameters:
                    environment: dev
                    awsCredentials: "Apollo-AWS-Dev-Apollo"

  ##############################################################################################
  # Stage: Deploy to the Test Environment
  #
  # - It is assumed that the container images have been pushed to Dev ECR in the Build Stage
  # - This stage will pull the container images from Dev ECR and then push to Test ECR
  # - This stage will use a template for the deployment job
  # - This stage can only be executed from the main branch
  # - This stage will reference the SourceHub-Test environment which may require approvals and
  #   other policies configured outside of this Pipeline.
  ##############################################################################################
  - stage: test
    displayName: Test Stage
    dependsOn: development
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - deployment: tst_deployment
        displayName: Deploy to SourceHub Test
        environment: SourceHub-Test
        strategy:
          runOnce:
            deploy:
              steps:
                ##
                # Pull SourceHub App Image from Dev ECR
                ##
                - task: ECRPullImage@1
                  displayName: Pull SourceHub App Image
                  inputs:
                    awsCredentials: "Apollo-AWS-Dev-Apollo"
                    regionName: "us-east-1"
                    repository: "sourcehub-app"
                    imageSource: "imagetag"
                    imageTag: "$(Build.SourceVersion)"
                    outputVariable: "DevImageId"

                ##
                # Push SourceHub App Image to Test ECR
                ##
                - task: ECRPushImage@1
                  displayName: Push SourceHub App Image to ECR as SourceVersion
                  inputs:
                    awsCredentials: "Apollo-AWS-Test-Apollo"
                    regionName: "us-east-1"
                    imageSource: "imageid"
                    sourceImageId: $(DevImageId)
                    repositoryName: "sourcehub-app"
                    pushTag: "$(Build.SourceVersion)"

                ##
                # Deploy SourceHub to Test environment
                ##
                - template: .azure-pipelines/source-hub.deploy.yml
                  parameters:
                    environment: tst
                    awsCredentials: "Apollo-AWS-Test-Apollo"

  ##############################################################################################
  # Stage: Deploy to the Prod Environment
  #
  # - It is assumed that the container images have been pushed to Dev ECR in the Build Stage
  # - This stage will pull the container images from Dev ECR and then push to Prod ECR
  # - This stage will use a template for the deployment job
  # - This stage can only be executed from a tag matching pattern 'v*'
  # - This stage will reference the SourceHub-Prod environment which may require approvals and
  #   other policies configured outside of this Pipeline.
  ##############################################################################################
  - stage: production
    displayName: Production Stage
    dependsOn: test
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - deployment: prd_deployment
        displayName: Deploy to SourceHub Prod
        environment: SourceHub-Prod
        strategy:
          runOnce:
            deploy:
              steps:
                ##
                # Pull SourceHub App Image from Dev ECR
                ##
                - task: ECRPullImage@1
                  displayName: Pull SourceHub App Image
                  inputs:
                    awsCredentials: "Apollo-AWS-Dev-Apollo"
                    regionName: "us-east-1"
                    repository: "sourcehub-app"
                    imageSource: "imagetag"
                    imageTag: "$(Build.SourceVersion)"
                    outputVariable: "DevImageId"

                ##
                # Push SourceHub App Image to Prod ECR
                ##
                - task: ECRPushImage@1
                  displayName: Push SourceHub App Image to ECR as SourceVersion
                  inputs:
                    awsCredentials: "Apollo-AWS-Prod-Apollo"
                    regionName: "us-east-1"
                    imageSource: "imageid"
                    sourceImageId: $(DevImageId)
                    repositoryName: "sourcehub-app"
                    pushTag: "$(Build.SourceVersion)"

                ##
                # Deploy SourceHub to Prod environment
                ##
                - template: .azure-pipelines/source-hub.deploy.yml
                  parameters:
                    environment: prd
                    awsCredentials: "Apollo-AWS-Prod-Apollo"
