version:  "3.9"
services:
  dev:
    image: sourcehub-dev:latest
    command: sleep infinity
    ports:
      - "8000:8000"
    environment:
      SSH_AUTH_SOCK: $SSH_AUTH_SOCK
    volumes:
      - dev:/home/user/workspace
      - type: bind
        source: $SSH_AUTH_SOCK
        target: $SSH_AUTH_SOCK
  mongo:
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    command: "mongod --dbpath /data/db"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: sh -c "redis-server --maxmemory 512mb --requirepass redis --maxmemory-policy allkeys-lfu"
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data
    command: minio server --console-address ":9001" /data

volumes:
  mongo:
  minio:
  dev:
    name: mbrown-dev
