version: "3.9"
services:
  opensearch-node:
    image: public.ecr.aws/opensearchproject/opensearch:2.3.0
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch-node:/usr/share/opensearch/data

  opensearch-dashboards:
    image: public.ecr.aws/opensearchproject/opensearch-dashboards:2.3.0
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node:9200"]'

volumes:
  opensearch-node:
