version: "3.9"
services:
  mongo:
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    command: "mongod --dbpath /data/db"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: sh -c "redis-server --maxmemory 512mb --requirepass redis --maxmemory-policy allkeys-lfu"

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data
    command: minio server --console-address ":9001" /data

  sqs:
    container_name: sqs
    image: softwaremill/elasticmq-native:1.3.13
    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf
    ports:
      - "9324:9324"
      - "9325:9325"

  taskworker_sync:
    container_name: taskworker_sync
    build:
      context: ../
      dockerfile: ./backend/taskworker_sync/Dockerfile
    ports:
      - "7070:8080"
    env_file:
      - ../backend/taskworker_sync/local.env
    entrypoint: ["/app/aws-lambda-rie", "python", "-m", "awslambdaric"]
    command: "main.handler"

volumes:
  mongo:
  minio:
