import { Button, Checkbox, Drawer, Form, Input } from 'antd';
import { DocDocumentLocation } from '../doc_documents/locations/types';
import {
  useUpdatePayerFamilyMutation,
  useLazyGetPayerFamilyByNameQuery,
  useGetPayerFamilyQuery,
} from './payerFamilyApi';
import { Rule } from 'antd/lib/form';
import { useForm } from 'antd/lib/form/Form';
import { useCallback, useState } from 'react';
import { PayerFamilyInfoForm } from './PayerFamilyInfoForm';
import { PayerFamily } from './types';
import { CloseOutlined, WarningFilled } from '@ant-design/icons';
import { useLazyGetPayerBackboneByLIdQuery } from '../payer-backbone/payerBackboneApi';
import { FormInstance } from 'antd/es/form/Form';

interface PayerFamilyCreateDrawerPropTypes {
  location: DocDocumentLocation | undefined;
  payer_family_id: string;
  open?: boolean;
  onClose: () => void;
  onSave: (updatedPayerFamily: PayerFamily) => void;
}

export const PayerFamilyEditDrawer = (props: PayerFamilyCreateDrawerPropTypes) => {
  const { location, onClose, onSave, open, payer_family_id } = props;
  const [form] = useForm();
  const { data: payerFamily } = useGetPayerFamilyQuery(payer_family_id, { skip: !payer_family_id });
  const [getPayerFamilyByName] = useLazyGetPayerFamilyByNameQuery();
  const [getPayerName] = useLazyGetPayerBackboneByLIdQuery();
  const [payerInfoError, setPayerInfoError] = useState<boolean>(false);
  const [updatePayerFamily, { isLoading }] = useUpdatePayerFamilyMutation();

  const autoGenerated = Form.useWatch('auto_generated', form);

  const handlePlanChange = () => {
    form.setFieldsValue({ payer_ids: [] });
  };

  const onSubmit = useCallback(async () => {
    let { payer_type, payer_ids, channels, benefits, plan_types, regions } =
      form.getFieldsValue(true);
    if (
      !payer_ids?.length &&
      !channels?.length &&
      !benefits?.length &&
      !plan_types?.length &&
      !regions?.length
    ) {
      setPayerInfoError(true);
      return;
    }
    if (form.getFieldValue('auto_generated')) {
      let getPayerNameVals = async () => {
        const payers: any = [];
        for (let i = 0; i < payer_ids.length; i++) {
          const { data } = await getPayerName({ payerType: payer_type, id: payer_ids[i] });
          payers.push(data?.name);
        }
        return payers;
      };
      let payerNames;
      if (payer_ids && payer_ids[0] !== '') {
        payerNames = await getPayerNameVals();
      }

      const newName = [regions, plan_types, benefits, channels, payerNames]
        .filter((vals: any) => (!vals || vals.length === 0 ? false : true))
        .join(' | ');
      form.setFieldsValue({ name: newName });
    }
    form.submit();
  }, [form, getPayerName]);

  const onFinish = useCallback(
    async (values: Partial<PayerFamily>) => {
      const payerFamily = await updatePayerFamily({ ...values, _id: payer_family_id }).unwrap();
      onSave(payerFamily);
      form.resetFields();
    },
    [updatePayerFamily, onSave, form, payer_family_id]
  );

  if (!location || !payerFamily) {
    return <></>;
  }

  return (
    <Drawer
      open={open}
      title={<>Edit Payer Family for {location.site_name}</>}
      width="30%"
      placement="left"
      closable={false}
      mask={false}
      extra={
        <Button type="text" onClick={onClose}>
          <CloseOutlined />
        </Button>
      }
    >
      <Form
        form={form}
        initialValues={payerFamily}
        layout="vertical"
        disabled={isLoading}
        autoComplete="off"
        requiredMark={false}
        validateTrigger={['onBlur']}
        onFinish={onFinish}
      >
        <div className="flex">
          <div className="flex-1 mt-2 mb-4">
            <h3>Site</h3>
            <div>{location.site_name}</div>
          </div>
        </div>
        <Form.Item
          label="Name"
          name="name"
          className="w-96 mr-5"
          rules={[
            { required: true, message: 'Please input a payer family name' },
            mustBeUnique(getPayerFamilyByName, payer_family_id, form),
          ]}
        >
          <Input disabled={autoGenerated} />
        </Form.Item>
        {autoGenerated ? 'Custom name will be generated on submission' : ''}
        <Input.Group className="space-x-2 flex">
          <Form.Item valuePropName="checked" name="auto_generated">
            <Checkbox>Auto Generate</Checkbox>
          </Form.Item>
        </Input.Group>

        <PayerFamilyInfoForm handlePlanChange={handlePlanChange} />
        <div className="space-x-2 flex justify-end">
          {payerInfoError ? (
            <>
              <WarningFilled className="text-red-600" />
              <span className="text-red-600">At least one payer value is required</span>
            </>
          ) : null}{' '}
          <Button onClick={onClose}>Cancel</Button>
          <Button type="primary" onClick={onSubmit} loading={isLoading}>
            Submit
          </Button>
        </div>
      </Form>
    </Drawer>
  );
};

// asyncValidator because rtk query makes this tough without hooks/dispatch
function mustBeUnique(asyncValidator: Function, currentPayerFamilyId: string, form: FormInstance) {
  return {
    async validator(_rule: Rule, value: string) {
      const { data: payerFamily } = await asyncValidator({ name: value });

      if (!payerFamily) {
        return Promise.resolve();
      }

      if (currentPayerFamilyId === payerFamily._id && value.split('').includes('|')) {
        if (value === payerFamily.name.toLowerCase()) {
          return Promise.reject(`Payer family name "${payerFamily.name}" already exists`);
        } else {
          return Promise.resolve('');
        }
      } else if (
        currentPayerFamilyId === payerFamily._id &&
        value !== payerFamily.name.toLowerCase() &&
        value !== payerFamily.name.toUpperCase()
      ) {
        return Promise.resolve();
      } else {
        return Promise.reject(`Payer family name "${payerFamily.name}" already exists`);
      }
    },
  };
}
