import { Checkbox, Form, Input } from 'antd';
import { FormInstance } from 'antd/es/form/Form';
import { Rule } from 'antd/lib/form';
import { useForm } from 'antd/lib/form/Form';
import { useCallback } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { MainLayout } from '../../components';
import { PayerEditSubmitComponent } from './PayerEditSubmitComponent';
import {
  useGetPayerFamilyQuery,
  useLazyGetPayerFamilyByNameQuery,
  useUpdatePayerFamilyMutation,
} from './payerFamilyApi';
import { PayerFamilyInfoForm } from './PayerFamilyInfoForm';
import { PayerFamily } from './types';

export const PayerFamilyEditPage = () => {
  const params = useParams();
  const payerFamilyId = params.payerFamilyId;

  const [form] = useForm();
  const navigate = useNavigate();
  const { data: payerFamily } = useGetPayerFamilyQuery(payerFamilyId);
  const [getPayerFamilyByName] = useLazyGetPayerFamilyByNameQuery();
  const autoGenerated = Form.useWatch('auto_generated', form);
  const [updatePayerFamily, { isLoading }] = useUpdatePayerFamilyMutation();

  const onFinish = useCallback(
    async (values: Partial<PayerFamily>) => {
      await updatePayerFamily({ ...values, _id: payerFamilyId }).unwrap();
      form.resetFields();
      navigate('/payer-family');
    },
    [updatePayerFamily, form, payerFamilyId, navigate]
  );

  if (!payerFamilyId || !payerFamily) {
    return <></>;
  }

  return (
    <MainLayout sectionToolbar={<PayerEditSubmitComponent form={form} />}>
      <div className="flex ml-5 space-x-4 overflow-auto flex-grow">
        <Form
          form={form}
          layout="vertical"
          disabled={isLoading}
          autoComplete="off"
          requiredMark={false}
          validateTrigger={['onBlur']}
          onFinish={onFinish}
          initialValues={payerFamily}
        >
          <Form.Item
            label="Name"
            name="name"
            className="w-96"
            rules={[
              { required: true, message: 'Please input a payer family name' },
              mustBeUnique(getPayerFamilyByName, payerFamilyId, form),
            ]}
          >
            <Input disabled={autoGenerated} />
          </Form.Item>
          Custom Name
          <Input.Group className="space-x-2 flex"></Input.Group>
          {autoGenerated ? 'Custom name will be generated on submission' : ''}
          <Input.Group className="space-x-2 flex">
            <Form.Item valuePropName="checked" name="auto_generated">
              <Checkbox>Auto Generate</Checkbox>
            </Form.Item>
          </Input.Group>
          <PayerFamilyInfoForm />
        </Form>
      </div>
    </MainLayout>
  );
};

// asyncValidator because rtk query makes this tough without hooks/dispatch
function mustBeUnique(asyncValidator: Function, currentPayerFamilyId: string, form: FormInstance) {
  return {
    async validator(_rule: Rule, value: string) {
      const { data: payerFamily } = await asyncValidator({ name: value });

      if (!payerFamily) {
        return Promise.resolve();
      }

      if (currentPayerFamilyId === payerFamily._id && value.split('').includes('|')) {
        if (value === payerFamily.name.toLowerCase()) {
          return Promise.reject(`Payer family name "${payerFamily.name}" already exists`);
        } else {
          return Promise.resolve('');
        }
      } else if (
        currentPayerFamilyId === payerFamily._id &&
        value !== payerFamily.name.toLowerCase() &&
        value !== payerFamily.name.toUpperCase()
      ) {
        return Promise.resolve();
      } else {
        return Promise.reject(`Payer family name "${payerFamily.name}" already exists`);
      }
    },
  };
}
