steps:
  ## Pull Latest SourceHub App Image from ECR if it exists. This will help improve build time of the App image
  - task: ECRPullImage@1
    displayName: Pull SourceHub App Image
    inputs:
      awsCredentials: "Apollo-AWS-Dev-Apollo"
      regionName: 'us-east-1'
      repository: 'sourcehub-app'
      imageSource: 'imagetag'
      imageTag: 'latest'
    continueOnError: true

  - task: Docker@2
    displayName: Build SourceHub App Image
    inputs:
      command: build
      repository: sourcehub-app
      Dockerfile: Docker/app.Dockerfile
      buildContext: $(Build.SourcesDirectory)
      arguments: '--cache-from 307744843177.dkr.ecr.us-east-1.amazonaws.com/sourcehub-app:latest --build-arg BUILDKIT_INLINE_CACHE=1'
      tags: |
        $(Build.BuildNumber)
        $(Build.SourceVersion)
        latest